# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-14 08:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('summary', models.TextField()),
                ('content', models.TextField()),
                ('link', models.TextField()),
                ('read', models.BooleanField()),
                ('favorite', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('url', models.TextField()),
                ('etag', models.CharField(default='', max_length=50)),
                ('modified', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='feed',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedr.Source'),
        ),
    ]
