# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-14 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='etag',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='source',
            name='modified',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
