# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-14 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedr', '0002_auto_20151214_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='pubDate',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='feed',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
    ]
